# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/pamelaherrera/Desktop/Muller_Lab/biogui/biogui/biogui/resources/cp2130_data_source_config_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLineEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_Cp2130ConfigWidget(object):
    def setupUi(self, Cp2130ConfigWidget):
        Cp2130ConfigWidget.setObjectName("Cp2130ConfigWidget")
        Cp2130ConfigWidget.resize(400, 62)
        self.formLayout = QtWidgets.QFormLayout(Cp2130ConfigWidget)
        self.formLayout.setObjectName("formLayout")
        self.label1 = QtWidgets.QLabel(Cp2130ConfigWidget)
        self.label1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cp2130ComboBox = QtWidgets.QComboBox(Cp2130ConfigWidget)
        self.cp2130ComboBox.setObjectName("cp2130ComboBox")
        self.horizontalLayout.addWidget(self.cp2130ComboBox)
        self.rescancp2130Button = QtWidgets.QPushButton(Cp2130ConfigWidget)
        self.rescancp2130Button.setText("")
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.rescancp2130Button.setIcon(icon)
        self.rescancp2130Button.setObjectName("rescancp2130Button")
        self.horizontalLayout.addWidget(self.rescancp2130Button)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Cp2130ConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(Cp2130ConfigWidget)
        Cp2130ConfigWidget.setTabOrder(self.cp2130ComboBox, self.rescancp2130Button)

    def retranslateUi(self, Cp2130ConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        Cp2130ConfigWidget.setWindowTitle(_translate("Cp2130ConfigWidget", "Serial Data Source Configuration"))
        self.label1.setText(_translate("Cp2130ConfigWidget", "USB Devices:"))
        self.cp2130ComboBox.setToolTip(_translate("Cp2130ConfigWidget", "List of available serial ports"))
        self.rescancp2130Button.setToolTip(_translate("Cp2130ConfigWidget", "Rescan serial ports"))

